### ISSUE TITLE
Error: spawn convert ENOENT

### ISSUE THREAD

**Issue by christianhaller** [wildlyinaccurate/whoopsie#23]
What am I doing wrong?

`whoopsie gallery test/whoopsie.yaml --verbose`

```
Capturing http://www.bbc.co.uk/news/ at 320px
Capturing http://www.test.bbc.co.uk/news/ at 320px
Capturing http://www.bbc.co.uk/news/ at 600px
Capturing http://www.test.bbc.co.uk/news/ at 600px
Capturing http://www.bbc.co.uk/news/ at 1020px
Capturing http://www.test.bbc.co.uk/news/ at 1020px
Capturing http://www.bbc.co.uk/news/technology at 320px
Capturing http://www.test.bbc.co.uk/news/technology at 320px
Capturing http://www.bbc.co.uk/news/technology at 600px
Capturing http://www.test.bbc.co.uk/news/technology at 600px
Capturing http://www.bbc.co.uk/news/technology at 1020px
Capturing http://www.test.bbc.co.uk/news/technology at 1020px
Capturing http://www.bbc.co.uk/news/technology-36387563 at 320px
Capturing http://www.test.bbc.co.uk/news/technology-36387563 at 320px
Capturing http://www.bbc.co.uk/news/technology-36387563 at 600px
Capturing http://www.test.bbc.co.uk/news/technology-36387563 at 600px
Comparing captures of http://www.bbc.co.uk/news/technology-36387563 and http://www.test.bbc.co.uk/news/technology-36387563 at 320px
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn convert ENOENT
    at exports._errnoException (util.js:1012:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

| Tool |  Version |
| --- | --- |
| node | v6.3.1 |
| npm | 3.10.6 |
| Whoopsie |  v0.5.0 |
| OSX |  10.11.4 |

**Comment by wildlyinaccurate** [comment]
Ah, I may have missed an important step in the README! Can you show me the output of `convert -version`? I suspect you either don't have imagemagick installed, or it might be an incompatible version.

**Comment by christianhaller** [comment]
Oh, there was no ImageMagick on my system. I missed that.
After installing via MacPorts, it says:

`Version: ImageMagick 6.9.5-0 Q16 x86_64 2016-07-28`

Now I have the same error I saw in docker (https://github.com/wildlyinaccurate/whoopsie/issues/24):

```
Comparing captures of bri.dev/patterns/03-templates-00-homepage/03-templates-00-homepage.html?testZone=develop and bri.dev/patterns/03-templates-00-homepage/03-templates-00-homepage.html?testZone=develop at 1020px
Unhandled rejection convert: geometry does not contain image `/var/tmp/magick-47606DzXoMkeNz5ia' @ warning/attribute.c/GetImageBoundingBox/247.
```
